# Generated by Django 5.0.2 on 2024-04-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cmobile', models.CharField(max_length=15)),
                ('caddress', models.TextField()),
                ('cmtype', models.CharField(max_length=20)),
                ('cperiod', models.CharField(max_length=20)),
                ('cjoindate', models.DateField()),
                ('cpaymode', models.CharField(max_length=20)),
                ('tamount', models.CharField(max_length=10)),
            ],
        ),
    ]
