# Generated by Django 5.0.2 on 2024-04-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tifin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlistmodel',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
