# Generated by Django 5.0.2 on 2024-04-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tifin_app', '0002_customerlistmodel_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abimg', models.ImageField(upload_to='static/user/uploads/')),
                ('abdis', models.TextField()),
            ],
        ),
    ]
