# Generated by Django 5.0.2 on 2024-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tifin_app', '0004_gallerymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderimg', models.ImageField(upload_to='static/user/uploads/')),
            ],
        ),
    ]
