# Generated by Django 5.0.2 on 2024-04-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tifin_app', '0005_slidermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctname', models.CharField(max_length=100)),
                ('ctmno', models.CharField(max_length=15)),
                ('ctsubject', models.CharField(max_length=100)),
            ],
        ),
    ]
