# Generated by Django 5.0.2 on 2024-04-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tifin_app', '0006_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='ctemail',
            field=models.EmailField(default='true', max_length=254),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='ctmsg',
            field=models.TextField(default='true'),
        ),
    ]
