# Generated by Django 5.0.2 on 2024-04-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tifin_app', '0007_contactmodel_ctemail_contactmodel_ctmsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaincourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcimg', models.ImageField(upload_to='static/user/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='RiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riceimg', models.ImageField(upload_to='static/user/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='RotiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotiimg', models.ImageField(upload_to='static/user/uploads/')),
            ],
        ),
    ]
